server:
  port: 8762


eureka:
  instance:
    hostname: eureka-server-two
  client:
    service-url:
      defaultZone: http://eureka-server-one:8761/eureka
    fetch-registry: false   # 是否拉取注册信息
    register-with-eureka: false   # 是否注册到eureka


spring:
  application:
    name: eureka-servers-two