server:
  port: 8763


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-one:8761/eureka, http://eureka-server-two:8762/eureka
    register-with-eureka: true #注册
    fetch-registry: false #拉取


spring:
  application:
    name: eureka-client
